config/routes.rb
Rails.application.routes.draw do
  get 'brick_shipments/index'

  get 'brick_shipments/new'

  get 'brick_shipments/create'

  root 'static_pages#home'
  #get 'static_pages/about'
  get 'about' => 'static_pages#about'
  get 'admin' => 'static_pages#admin'
  get 'report' => 'static_pages#report'
  post 'submit' => 'static_pages#submit'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'clay_shipments/rearrange' => 'clay_shipments#rearrange'
  get 'clay_shipments/finish' => 'clay_shipments#finish'

  get 'brick_shipments/bake' => 'brick_shipments#bake'

  resources :users
  resources :clay_shipments, only: [:new, :create, :index, :edit, :show]
  resources :brick_shipments, only: [:new, :create, :index, :edit]
  resources :account_activations, only: [:edit]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :check_admin, only: [:admin]

  #The home page, with all the global stats
  def home
    @clays = ClayShipment.count
    @bricks = 0
    @towers = 0
  end

  def about
  end

  def admin
  end

  #Page for the reporting problems page
  def report
  	@error = NewsItem.new
  end

  #Handles posts to from problem reports, makes them into an update for the admins
  def submit
  	@message = NewsItem.new(error_params)
    #No shenagins, you hear!
    @message.message = ActionView::Base.full_sanitizer.sanitize(@message.message)
    #Gives this message to all users
  	@message.users << User.where(admin: true)
  	@message.msg_type = "error_report"
  	if @message.save
  		flash[:success] = "Thank you for your report"
  		redirect_to '/'
  	else
  		flash[:danger] = "There was an error with the error reporting. That's just fucked up."
  		render 'report'
  	end
  end

  private
  	def error_params
  		params.require(:news_item).permit(:message)
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About Tower Brick Lightning") %>
<h1>What is Tower Brick Lightning?</h1>
<p>
	Long ago, there were the Gods. And they were kind of jerks! They kept cursing people all the time: blighting the land, killing our crops, making bees follow us around all the time, melting our skin, all sorts of mean stuff. One day we got tired of that and decided to build a great big tower, so we could travel up to the heavens and punch the gods right in the kisser!
</p>
<p>
	However, the Gods caught wise to this plan and cursed us again! Now we can't communicate! But are we gonna let that stop us? No way! We ain't quitters. We're going to build that tower all the same!
</p>
<p>
	Tower Brick Lightning is a massively multiplayer browser based game about crafting, construction, and communication. Work with your fellow builders to build the tower up to the heavens, while trying to collaborate best you can despite the limitations the gods have cursed you with.
</p>
<p>
	Coming soon to a browser near you
</p>

app/views/static_pages/admin.html.erb
<h1>Admin Page</h1>
I ain't making this look nice, nobody but us chickens in here<br/>
<%= link_to "All Users", users_path %><br/>
<%= link_to "All Clay Shipments", clay_shipments_path %><br/>

app/views/static_pages/home.html.erb
<% provide(:title, "Tower Brick Lightning") %>
<% if !logged_in? %>
	<div class = "center jumbotron">
		<h1>Tower Brick Lightning</h1>
		<p>
			An exciting tower building confusion game coming soon to a browser near you!
		</p>

		<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	</div>
<% else %>
	<h1><%= current_user.name %></h1>
	<div id = "information">
		<div id = "player_status">
			Actions: <%= current_user.actions %>
		</div>
		<div id = "siderbar">
			<div id = "global_stats" class = "box">
				Total Clay Shipments: <%= @clays %></br>
				Total Brick Shipments: <%= @bricks %></br>
				Total Tower Levels: <%= @towers %></br>
			</div>
			<div id = "links" class = "box">
				<%= link_to "Mining", new_clay_shipment_path %><br/>
				<%= link_to "Brick Baking", '#' %><br/>
				<%= link_to "Tower Build", '#' %><br/>
				<%= link_to "The Tower", '#' %><br/>
				<%= link_to "Profile", current_user %><br/>
				<%= link_to "Settings", edit_user_path(current_user) %><br/>
				<% if current_user.admin %>
					<%= link_to "Admin", '/admin' %>
				<% end %>
			</div>
		</div>
	</div>
	<div id = "news_feed">
		<h3>Updates</h3>
		<ul>
			<% current_user.news_items.order(created_at: :desc).each do |news| %>
				<li class = "<%= news.msg_type %>"><%= news.created_at.strftime("%_m/%-d, %l:%M %p")%>: <%= news.message.html_safe %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/report.html.erb
<% provide(:title, "Report Errors") %>

<h1>Problems?</h1>
Please tell me about any problems you have. Please include your user name with the message.
<%= form_for(@error, url: '/submit') do |f| %>
	<%= f.label :message %><br/>
	<%= f.text_area :message, size: "20x10" %><br/>

	<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>