config/routes.rb
Rails.application.routes.draw do
  get 'brick_shipments/index'

  get 'brick_shipments/new'

  get 'brick_shipments/create'

  root 'static_pages#home'
  #get 'static_pages/about'
  get 'about' => 'static_pages#about'
  get 'admin' => 'static_pages#admin'
  get 'report' => 'static_pages#report'
  post 'submit' => 'static_pages#submit'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'clay_shipments/rearrange' => 'clay_shipments#rearrange'
  get 'clay_shipments/finish' => 'clay_shipments#finish'

  get 'brick_shipments/bake' => 'brick_shipments#bake'

  resources :users
  resources :clay_shipments, only: [:new, :create, :index, :edit, :show]
  resources :brick_shipments, only: [:new, :create, :index, :edit]
  resources :account_activations, only: [:edit]
end

app/models/clay_shipment.rb
class ClayShipment < ActiveRecord::Base
	belongs_to :user
	serialize :clay, Array
	#validates :message, presence: true
	after_initialize :init

	def init
		if clay[0].nil?
			Rails.configuration.x.pack_total.times do
				self.clay << -1
			end
		end
	end

	def self.clear_out
		ClayShipment.where(message: nil).each do |shipment|
			shipment.delete
		end
	end

	#Picks N random shipments and returns them
	def self.random(number)
		ClayShipment.where(used: nil).where.not(message: nil).order("RANDOM()").limit(number)
	end

	def hide_clay
		@secret_clay = []
		clay.each do |i|
			if i == -1
				@secret_clay << -1
			else
				@secret_clay << 1
			end
		end
		return @secret_clay
	end
end

app/controllers/clay_shipments_controller.rb
class ClayShipmentsController < ApplicationController
  before_action :logged_in_user
  before_action :has_actions, only: [:new]
  before_action :check_admin, only: [:index]
  include ClayShipmentsHelper

  def new
    @finished = session["finished_clay"]
    @glyphs = Glyph.all
  	#Make n mines and save their id's in the session
    create_mines
  	#Creates a new clay shipment, if necessary
    if session["clay_shipment"].nil? || !ClayShipment.exists?(session["clay_shipment"])
  	  @shipment = ClayShipment.create(user: current_user)
      session["clay_shipment"] = @shipment.id
    else
      @shipment = ClayShipment.find(session["clay_shipment"])
    end
  end

  def index
    @shipments = ClayShipment.all
    @glyphs = Glyph.all
  end

  def create
    @shipment = ClayShipment.find(session["clay_shipment"])
    @shipment.message = params[:shipment][:message]
    #This needs to check that the message isn't blank
    if @shipment.message.blank?
      flash[:danger] = "Clay Shipments must include a message."
      redirect_to :back
      #render js: "$('#alert').text('Clay shipments must include a message');"
    elsif @shipment.save
      flash[:success] = "Clay Shipment sent! Good job."
      clear_session
      current_user.actions -= 1
      current_user.save
      redirect_to root_url
    else
      render "new"
    end
  end

  def edit
    extract_clay

    respond_to do |format|
      format.js
    end
  end

  def rearrange
    shipment = ClayShipment.find(session["clay_shipment"])
    shipment.clay[params[:a].to_i], shipment.clay[params[:b].to_i] = shipment.clay[params[:b].to_i], shipment.clay[params[:a].to_i]
    shipment.save
    render :nothing => true
  end

  def show
    if request.xhr?
      if params["type"] == "hidden"
        @clay = ClayShipment.find(session[params["id"]]).hide_clay
      elsif params["type"] == "clay"
        shipment = ClayShipment.find(session[params["id"]])
        @clay = shipment.clay[params["index"].to_i]
        puts @clay
        shipment.clay[params["index"].to_i] = Rails.configuration.x.no_clay
        shipment.save
      end
      respond_to do |format|
        format.json { render json: @clay }
      end
    end
  end

  def finish
    shipment = ClayShipment.find(session["clay_shipment"])
    if shipment.clay.count(-1) <= 4
      session["finished_clay"] = true
      @glyphs = Glyph.all
      @finished = true;
    else
      @finished = false;
    end

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/clay_shipments_helper.rb
include ActionView::Helpers::TextHelper

module ClayShipmentsHelper

	def create_mines
		Rails.configuration.x.total_mines.times do |i|
			if session["mine#{i}"].nil? || !Mine.exists?(session["mine#{i}"])
				session["mine#{i}"] = Mine.new_mine.id
			end	
		end
	end

	def extract_clay
		@mine = Mine.find(session[params[:id]])
	    @shipment = ClayShipment.find(session["clay_shipment"])
	    red_clay = 0;
	    brown_clay = 0;
	    black_clay = 0;

	    Rails.configuration.x.mine_actions.times do
	    	if @shipment.clay.include?(Rails.configuration.x.no_clay)
	    		r = rand(Rails.configuration.x.clay_types)
		    	case r
		    	when Rails.configuration.x.red
		    		if @mine.red_clay > 0
		      			@mine.update(red_clay: @mine.red_clay - 1)
		      			@shipment.clay[@shipment.clay.index(-1)] = Rails.configuration.x.red
		      			red_clay += 1
		    		end
		    	when Rails.configuration.x.brown
		    		if @mine.brown_clay > 0
		      			@mine.update(brown_clay: @mine.brown_clay - 1)
		      			@shipment.clay[@shipment.clay.index(-1)] = Rails.configuration.x.brown
		      			brown_clay += 1
		    		end
		    	when Rails.configuration.x.black
		    		if @mine.black_clay > 0
		      			@mine.update(black_clay: @mine.black_clay - 1)
 		      			@shipment.clay[@shipment.clay.index(-1)] = Rails.configuration.x.black
		      			black_clay += 1
		    		end
		    	else
		    		puts "extract_clay put out a case that shouldn't: #{r}"
		    	end
	    	else
	    	end
	    end
	    @shipment.save()
	    write_update(red_clay, brown_clay, black_clay)
	end

	def write_update(red, brown, black)
		@update = ""
		if (red + brown + black) == 0
			if @shipment.clay.include?(Rails.configuration.x.no_clay)
				@update += "That mine is tapped out."
			end
		else
			@update = "You found "
			clays = []

			if red > 0
				clays << pluralize(red, 'red clay')
			end

			if brown > 0
				clays << pluralize(brown, 'brown clay')
			end

			if black > 0
				clays << pluralize(black, 'black clay')
			end

			@update += clays.to_sentence + "."
		end

		if !@shipment.clay.include?(Rails.configuration.x.no_clay)
			@update += " Your pack is full."
		end
	end

	def clear_session
		session["clay_shipment"] = nil
		Rails.configuration.x.total_mines.times do |i|
			Mine.find(session["mine#{i}"]).delete
			session["mine#{i}"] = nil
		end
		session["finished_clay"] = false
	end
end

app/views/clay_shipments/_clay_shipment.html.erb
<p>
	Created by: <%= clay_shipment.user.name %><br/>
	Created at: <%= clay_shipment.created_at %><br/>
	Id: <%= clay_shipment.id %><br/>
	Used: <%= clay_shipment.used %><br/>
	Message:
	<% if !clay_shipment.message.nil? %>
		<% clay_shipment.message.split(" ").each do |glyph| %>
			<% if @glyphs.exists?(glyph) %>
				<%= render partial: 'shared/glyph_read', locals: {glyph: @glyphs.find(glyph)} %>
			<% else %>
				(<%= glyph %>)
			<% end %>
		<% end %>
	<% end %>
	<br/>
	<% Rails.configuration.x.pack_height.times do |i| %>
		<% Rails.configuration.x.pack_width.times do |j| %>
			<% if clay_shipment.clay[i*Rails.configuration.x.pack_width + j] == Rails.configuration.x.red %>
				<div id = 'grid<%= i*Rails.configuration.x.pack_width + j %>' class = 'red grid clay'></div>
			<% elsif clay_shipment.clay[i*Rails.configuration.x.pack_width + j] == Rails.configuration.x.brown %>
				<div id = 'grid<%= i*Rails.configuration.x.pack_width + j %>' class = 'brown grid clay'></div>
			<% elsif clay_shipment.clay[i*Rails.configuration.x.pack_width + j] == Rails.configuration.x.black %>
				<div id = 'grid<%= i*Rails.configuration.x.pack_width + j %>' class = 'black grid clay'></div>
			<% else %>
				<div id = 'grid<%= i*Rails.configuration.x.pack_width + j %>' class = 'blank grid clay'></div>
			<% end %>
		<% end %>
		<br/>
	<% end %>
	<hr>
</p>

app/views/clay_shipments/edit.js.erb
// console.log("Editing mine id: <%= @mine.id %>");
// console.log("Editing clay shipment id: <%= @shipment.id %>");

<% @shipment.clay.each_with_index do |color, i| %>
	setGrid(<%= i %>, getColor(<%= color %>));
<% end %>

$("#alert").text("<%= @update %>");

function setGrid(i, color){
	if(i < <%= Rails.configuration.x.pack_total %>){
		$("#grid"+ i ).removeClass("blank red brown black").addClass(color);
	}else{
		console.log("You tried to add too many clays");
	}
}

function getColor(number){
	switch(number){
		case <%= Rails.configuration.x.red %>:
			return "red";
			break;
		case <%= Rails.configuration.x.brown %>:
			return "brown";
			break;
		case <%= Rails.configuration.x.black %>:
			return "black"
			break
		default:
			return "blank";
	}
}

app/views/clay_shipments/finish.js.erb
<% if @finished %>
	$(".mine").hide();
	$(".finish").hide();

	$(".content").append("<%= escape_javascript(
		render partial: 'shared/message_form', locals: {url: clay_shipments_path, glyphs: @glyphs}
		) %>");
<% else %>
	$("#alert").text("You must have at least four clays to submit.");	
<% end %>

app/views/clay_shipments/index.html.erb
<% provide(:title, "Clay Shipments") %>
<h1>Clay Shipments</h1>
<p>
	Total Clay Shipments: <%= @shipments.length %><br/>
	Unused Clay Shipments: <%= @shipments.where(used: nil).count %>
<p>

<h4>All Shipments</h4>
<%= render @shipments.order(created_at: :desc) %>

app/views/clay_shipments/new.html.erb
<% provide(:title, "MINING") %>
<p id = "alert">
	<% if !@finished %>
		It is time to go mining
	<% else %>
		Write a message to describe your clay shipment.
	<% end %>
</p>

<p id = "mines">
	<% if !@finished %>
		<% Rails.configuration.x.total_mines.times do |i| %>
			<%= button_to "MINE", edit_clay_shipment_path("mine#{i}"), method: "get", remote: true, form_class: "btn mine" %>
		<% end %>
	<% end %>
</p>

<p id = "pack">
	<% Rails.configuration.x.pack_height.times do |i| %>
		<% Rails.configuration.x.pack_width.times do |j| %>
			<% if @shipment.clay[i*Rails.configuration.x.pack_width + j] == Rails.configuration.x.red %>
				<div id = 'grid<%= i*Rails.configuration.x.pack_width + j %>' class = 'red grid clay'></div>
			<% elsif @shipment.clay[i*Rails.configuration.x.pack_width + j] == Rails.configuration.x.brown %>
				<div id = 'grid<%= i*Rails.configuration.x.pack_width + j %>' class = 'brown grid clay'></div>
			<% elsif @shipment.clay[i*Rails.configuration.x.pack_width + j] == Rails.configuration.x.black %>
				<div id = 'grid<%= i*Rails.configuration.x.pack_width + j %>' class = 'black grid clay'></div>
			<% else %>
				<div id = 'grid<%= i*Rails.configuration.x.pack_width + j %>' class = 'blank grid clay'></div>
			<% end %>
		<% end %>
		<br/>
	<% end %>
</p>

<% if !@finished %>
	<%= button_to "FINISH", '/clay_shipments/finish.js', method: "get", remote: true, 
		form_class: "btn finish" %>
<% end %>

<% if @finished %>
	<%= render partial: 'shared/message_form', locals: {url: clay_shipments_path, glyphs: @glyphs} %>
<% end %>