config/routes.rb
Rails.application.routes.draw do
  get 'brick_shipments/index'

  get 'brick_shipments/new'

  get 'brick_shipments/create'

  root 'static_pages#home'
  #get 'static_pages/about'
  get 'about' => 'static_pages#about'
  get 'admin' => 'static_pages#admin'
  get 'report' => 'static_pages#report'
  post 'submit' => 'static_pages#submit'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'clay_shipments/rearrange' => 'clay_shipments#rearrange'
  get 'clay_shipments/finish' => 'clay_shipments#finish'

  get 'brick_shipments/bake' => 'brick_shipments#bake'

  resources :users
  resources :clay_shipments, only: [:new, :create, :index, :edit, :show]
  resources :brick_shipments, only: [:new, :create, :index, :edit]
  resources :account_activations, only: [:edit]
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
	<div class = "alert alert-<%=message_type%>" >
		<%= message %>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class ="footer">
	<small>
		Tower Brick Lightning is made by <a href="http://www.thejhyde.zone/">J. Hyde</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", 	about_path %></li>
			<li><%= link_to "Report Problems", report_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
	<div class = "container">
		<%= link_to "TOWER BRICK LIGHTNING", root_path, id: "logo" %>
		<nav>
			<ul class = "nav navbar-nav navbar-right">
				<li><%= link_to "Home", 	root_path %></li>
				<% if logged_in? %>
					<li><%= link_to "Mine", new_clay_shipment_path %></li>
					<li><%= link_to "Bake", '#' %></li>
					<li><%= link_to "Build", '#' %></li>
					<li><%= link_to "Tower", '#' %></li>
					<li><%= link_to "Log Out", logout_path, method: "delete" %></li>
				<% else %>
					<li><%= link_to "About", 	about_path %></li>
					<li><%= link_to "Log in", 	login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= yield(:title) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	</head>
	<body class = "<%= controller_name%> <%= action_name %>">
		<%= render 'layouts/header' %>
		<div class = "content">
			<%= render 'layouts/flash' %>
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
		<%#= session.inspect if Rails.env.development? %>
	</body>
</html>